In [1]:
import pandas as pd
import numpy as np

In [2]:
output_dir = "runs/test/"

In [7]:
test = pd.read_csv('data/test_set_private.csv', names=['user_id'] + [f'item_id_{i}' for i in range(1,1001)])

In [8]:
test.head()

,user_id,item_id_1,item_id_2,item_id_3,item_id_4,item_id_5,item_id_6,item_id_7,item_id_8,item_id_9,...,item_id_991,item_id_992,item_id_993,item_id_994,item_id_995,item_id_996,item_id_997,item_id_998,item_id_999,item_id_1000
0,0a9Fr9I8Gr,boqO5yZLGn,8ZkMmPx7LA,lY9LS9tm2o,GlcugvT0Yc,CgxImEqsPz,Gob6GYLouL,IRvMMJ0b7w,40N3veG6jC,ZDcoul5cdR,...,Z8xiRnRjZD,5MwdFYt8z0,IzLVUKs7uQ,Ic5BpxKXZg,F9jblvzWuK,xvKZji6pWJ,arvytMaCpS,XC7SvTAElR,oWsTKxTtvA,iLKSmk2T06
1,Jg3UwpR1cA,FR8wGxRAuG,dYzjsJalSw,46UB3fKUvW,43pBc5JjXG,UMBBUX1BCV,QJMMePEj0j,bGCcG8kfTI,1S3CqINx38,iPCMUOS4gu,...,84YaBhvrnw,uUg3iZKEDz,VS9vm70j8u,mb8iada716,W4LaO2AnPF,oH6lYVrH2Z,RdMLs1XP8z,cjhX33aANo,JVR40qZevF,m5tbhqzC7m
2,k0mNOjn7pv,XY3JQdn2uK,VXSaWxoJhS,Jd9W82sCwm,APxSylqBUi,xSYbWMYXQ3,nO5G68rbFr,akZrO7ylK0,u2BPbQVjhn,0mCZtLlSSJ,...,LcT9aU6sDk,erjkmeJrO2,DtAWzeNoqo,9C1LcSgNrd,RfaOiwln47,EjaSqbgfWm,5MmscAd5ND,4CDZjAxiJ3,iPzOhrroRk,Or6J4bnaJo
3,Uw0zXc8Sr8,CZIxh1jK1E,HDkA9U2Xcw,B5Y4WsLlpa,TtcC5Je1JD,4CGmtKJuwQ,Q3UHYGUanE,ZtFOy1wdyW,GDKM1k4EhP,CxB3Ckr0Qg,...,UmYJDzVAm1,6c9wVM3C7n,yy78DDyFwz,JBWS6uOW6t,uFtLv6hcKO,Z8p8xxx0cx,Py42KZCHJP,ewfqfR6fiC,rdZDIeJ1ia,OgmtWQ39sq
4,vLDKNL74C4,geQIsKSQMq,Fv1Qr0KyxC,rOrsptpv8t,x9uKie7B9k,j3BAm5H5Ht,rMoQ4U14Bz,HszEQFR8mO,Vjl5VpE6mQ,Be0DFaA4f2,...,MUWZaAPDNT,rnp6yH6OD5,45KRQI5RJi,iPRCkgoeGJ,6PtfgezcfB,w83nfFLEQF,aD2c2V2wYx,Cu2tQGKjrm,Ec3YhNEIRi,ax59cfAF2Y

In [9]:
cluster = pd.read_csv('runs/simgcl/user_clusters.csv')
cluster.head()

      User ID  TSNE Component 1  TSNE Component 2  Cluster
0  tyviMi4b8Q        -14.119447        -35.864280        0
1  PGcvoaV6Gn        -55.866210         52.591460        1
2  vZK9GTxbNA         38.880062          1.507839        2
3  Sr1MiLP6VX        -16.879784         50.859344        1
4  y9iZADrbdu         38.975315         -8.565986        2

In [10]:
user_df = test.copy()
user_df = user_df.set_index('user_id')
cluster = cluster.set_index('User ID')
user_df = user_df.join(cluster)

In [11]:
user_df

,item_id_1,item_id_2,item_id_3,item_id_4,item_id_5,item_id_6,item_id_7,item_id_8,item_id_9,item_id_10,...,item_id_994,item_id_995,item_id_996,item_id_997,item_id_998,item_id_999,item_id_1000,TSNE Component 1,TSNE Component 2,Cluster
user_id,,,,,,,,,,,,,,,,,,,,,
0a9Fr9I8Gr,boqO5yZLGn,8ZkMmPx7LA,lY9LS9tm2o,GlcugvT0Yc,CgxImEqsPz,Gob6GYLouL,IRvMMJ0b7w,40N3veG6jC,ZDcoul5cdR,kAxCrN62Hf,...,Ic5BpxKXZg,F9jblvzWuK,xvKZji6pWJ,arvytMaCpS,XC7SvTAElR,oWsTKxTtvA,iLKSmk2T06,88.935356,11.679152,43
Jg3UwpR1cA,FR8wGxRAuG,dYzjsJalSw,46UB3fKUvW,43pBc5JjXG,UMBBUX1BCV,QJMMePEj0j,bGCcG8kfTI,1S3CqINx38,iPCMUOS4gu,aJRm92B22C,...,mb8iada716,W4LaO2AnPF,oH6lYVrH2Z,RdMLs1XP8z,cjhX33aANo,JVR40qZevF,m5tbhqzC7m,35.345448,-0.904080,2
k0mNOjn7pv,XY3JQdn2uK,VXSaWxoJhS,Jd9W82sCwm,APxSylqBUi,xSYbWMYXQ3,nO5G68rbFr,akZrO7ylK0,u2BPbQVjhn,0mCZtLlSSJ,Ajt4sg1KJ4,...,9C1LcSgNrd,RfaOiwln47,EjaSqbgfWm,5MmscAd5ND,4CDZjAxiJ3,iPzOhrroRk,Or6J4bnaJo,-74.450940,46.748680,146
Uw0zXc8Sr8,CZIxh1jK1E,HDkA9U2Xcw,B5Y4WsLlpa,TtcC5Je1JD,4CGmtKJuwQ,Q3UHYGUanE,ZtFOy1wdyW,GDKM1k4EhP,CxB3Ckr0Qg,qSayobQ897,...,JBWS6uOW6t,uFtLv6hcKO,Z8p8xxx0cx,Py42KZCHJP,ewfqfR6fiC,rdZDIeJ1ia,OgmtWQ39sq,42.048542,-18.871851,2
vLDKNL74C4,geQIsKSQMq,Fv1Qr0KyxC,rOrsptpv8t,x9uKie7B9k,j3BAm5H5Ht,rMoQ4U14Bz,HszEQFR8mO,Vjl5VpE6mQ,Be0DFaA4f2,PtaZwkYmBE,...,iPRCkgoeGJ,6PtfgezcfB,w83nfFLEQF,aD2c2V2wYx,Cu2tQGKjrm,Ec3YhNEIRi,ax59cfAF2Y,-55.759243,5.005085,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SIFzQe6gnn,1Qkjg4RArI,59BC4wI3Mk,19IKZkSsqa,vnpVwiqRii,XQcpbi336z,Cnix4ZUc2r,kOzdRop3Ar,HN6diHMr1i,FTfNEhzCMG,hkpfeF0PXQ,...,GoxXzgB7Q0,kavQ1mOVNr,1hIY7i8r8j,eqHobu9Yqj,TvY4Mry9Jq,FMbHiyRS9j,Z8DZIlk6Ba,-44.168365,-15.370557,19
fa6Y1KVdoh,ij8vIl3sTU,H1VD1AZpUS,DUHWb5PKRw,gfdGfr4gc0,nqs5kdaLhX,soKOs2RR1J,oCktdVhUqe,tzT4slvIwR,kaYzHeYCrC,usZweo2V23,...,yRVWYuvtq2,eev7RsNa8P,IkDPzM03Sx,XaNw8hYLjk,ghisamesER,spcaQOLgxo,0vVahjHuuC,11.693085,48.754870,60
xO9WRD2Zbm,NbD4ouH6Rl,Vh1rJPuLiq,HtHWRvbZIg,gpPUGpmysX,be8hMXp8wj,SglJUrnBNT,dDdO2jbzob,y9ijj4g9GT,Xy9HbjNlZM,rtoecSg3T9,...,KpiEA8pmw2,r7hfGuks2f,wprAMV2BLw,dOVqOXbGkT,bvXtJiSFJ5,yOhu2oTbSY,WbFJZJVHki,-31.440638,86.598366,4
EW403CecBe,xCX8amjYxc,orEoAYSfZV,F4mNp80jxO,7STS20efW3,WaYX8HzOd1,bnXGc9FRN4,bYRHBAZNYO,mASQOMlEYr,3NOCYQsk5S,SUEBoAPEJU,...,lAxFxvgOKQ,pvGUb7hgvt,Q7b1WBHm3R,8JeVX81aZq,k9F8pVYcuc,UqCFYQNiAh,nE2BeBrwMw,39.485218,-33.406105,33
Y4zCkSuqwM,DzXgVUZ7I4,szfoQCBsTH,81Oax4D8rb,4UbvEDPMKz,u77WUDHX0x,y5RE8letOT,xJTQyFOfXY,tez9YLSoMq,RSyiAhQl4f,rQGiImtEdd,...,YZEOkPeyqG,PRHZvjkfa4,X5AxItAQSC,8zwhsscAM4,X3aTjr6j1P,sSLNJG2mIp,s6Xxj549Td,-36.653286,-28.603294,14

In [12]:
from collections import Counter
def get_most_common_items_for_cluster(user_df, cluster_column='Cluster', item_columns=None):
    cluster_item_counts = {}

    # Iterate over each cluster
    for cluster in user_df[cluster_column].unique():
        # Get users in this cluster
        cluster_users = user_df[user_df[cluster_column] == cluster]
        
        # Get all item interactions for these users
        cluster_items = cluster_users[item_columns].values.flatten()
        
        # Count the frequency of each item (ignore NaN or empty interactions)
        cluster_items = [item for item in cluster_items if pd.notna(item)]
        item_counter = Counter(cluster_items)
        
        # Save the most common items in this cluster
        cluster_item_counts[cluster] = item_counter.most_common()
    
    return cluster_item_counts

item_columns = [f'item_id_{i+1}' for i in range(1000)] 
cluster_item_counts = get_most_common_items_for_cluster(user_df, item_columns=item_columns)

In [13]:
train = pd.read_csv("data/training_set.csv")
list_all_train_item = train["ItemId"].unique()
items_df = test[item_columns]
all_test_items = items_df.values.flatten()
all_test_items = set(all_test_items)
old_items = set(all_test_items).intersection(set(list_all_train_item))
new_items = all_test_items - old_items

In [14]:
new_items_dict = {}

for user_idx, user_id in enumerate(test["user_id"]):  # Assuming 'user_id' is the first column
    # Get the list of items the user has interacted with
    user_items = items_df.iloc[user_idx].values.tolist()
    
    # Filter out items that are NaN or empty
    user_items = [item for item in user_items if pd.notna(item) and item != '']
    
    # Find new items by checking which of the user's items are in `new_items`
    user_new_items = [item for item in user_items if item in new_items]
    
    # Add to the dictionary: user_id -> list of new items
    new_items_dict[user_id] = user_new_items

In [85]:
# new_items_dict

In [15]:
def recommend_items_for_user(user_id, cluster_item_counts, new_items_dict, user_df, item_columns, top_n=1000):
    # Get the user's cluster
    user_cluster = user_df.loc[user_id, 'Cluster']
    # Get the most common items in this cluster
    common_items = [(item, count) for item, count in cluster_item_counts[user_cluster]]
    common_items = pd.DataFrame(common_items, columns=['item_id', 'count'])
   
    # Get the new items for this user
    new_items = new_items_dict.get(user_id, [])
    recommended_items = common_items[common_items['item_id'].isin(new_items)]
    # print(recommended_items)
    recommended_items = recommended_items.sort_values(by='count', ascending=False)['item_id'].tolist()
    # Ensure the recommended list has 1000 items (pad with "empty" items if necessary)
    recommended_items += ["0"] * (top_n - len(recommended_items))  # Pad with empty strings
    # print(recommended_items)
    return recommended_items

# Create a list to hold all recommendations
recommendations = []

# Generate recommendations for each user
for user_id in user_df.index:
    recommended_items = recommend_items_for_user(user_id, cluster_item_counts, new_items_dict, user_df, item_columns)
    recommendations.append([user_id] + recommended_items)
# Convert the recommendations into a DataFrame
recommendations_df = pd.DataFrame(recommendations, columns=['user_id'] + [f'item_{i+1}' for i in range(1000)])

In [16]:
recommendations_df

,user_id,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,...,item_991,item_992,item_993,item_994,item_995,item_996,item_997,item_998,item_999,item_1000
0,0a9Fr9I8Gr,d3zkvaMRUK,pe8J4kCUnU,m86n5b37gT,P3oS2gPMdl,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Jg3UwpR1cA,6Q7nciMCbt,xYZPPE3kME,0b3wzAqwax,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,k0mNOjn7pv,dsWuSQynjf,lj9NIoNmvv,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Uw0zXc8Sr8,cX0ltv9cPl,qLk6lPTOpu,cAREfZ7vCi,xk1KK58iks,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,vLDKNL74C4,i4TSnkRWnB,7EyDo411mJ,4i9V4beNHt,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,SIFzQe6gnn,FTfNEhzCMG,wvPuwrf0mR,h4f3mLsZgS,30kRZEX4C6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4221,fa6Y1KVdoh,ZSZ7mk7kVH,H2kIsgN5NO,5StrBLrwwx,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4222,xO9WRD2Zbm,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4223,EW403CecBe,0b3wzAqwax,18ir0iOBPn,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4224,Y4zCkSuqwM,3ZZ64RpnDA,sSLNJG2mIp,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
import pandas as pd

last_1000_columns = recommendations_df.iloc[:, -1000:]

# Count rows where there is at least one non-zero value in the last 1000 columns
non_zero_rows = (last_1000_columns != "0").any(axis=1)

# Count the number of such rows
count_non_zero_rows = non_zero_rows.sum()

print("Number of rows with non-zero values in the last 1000 columns:", count_non_zero_rows)

Number of rows with non-zero values in the last 1000 columns: 3707

In [78]:
recommendations_df.to_csv('submission/predict_new.csv', header=None, index=None)

In [46]:
best = pd.read_csv('runs/private-test-attempt-1/LightGCN_predict.csv', names=['user_id'] + [f'item_id_{i}' for i in range(1,1001)])

# Add new by cluster to low_agreement_user

In [47]:
# Read keys from a file into a list
with open("data/low_agreement_user.txt", "r") as f:
    keys = [line.strip() for line in f.readlines()]
len(keys)

790

In [48]:
# best.loc[recommendations_df['item_1'] != "0", 'item_id_10'] = recommendations_df['item_1']
count = 0
for idx, row in best.iterrows():
    if row['user_id'] in keys:
        # Get the corresponding recommendation for this user
        recommendation = recommendations_df.loc[recommendations_df['user_id'] == row['user_id'], 'item_1'].values
        
        if recommendation and recommendation[0] != '0':  # Check if the recommendation is not '0'
            count += 1
        #     for i in range(9, 4, -1):  # Start from item_id_9 and shift down to item_id_2
        #         best.loc[idx, f'item_id_{i+1}'] = best.loc[idx, f'item_id_{i}']
            # Replace item_id_1 with item_1 from recommendations_df
            best.loc[idx, 'item_id_10'] = recommendation[0]
print(count)

695

In [44]:
best['item_id_10']

0       MndpaEak8s
1       uqpr0GYIc2
2       WFre1KvdmG
3       cX0ltv9cPl
4       8M2Gusvh40
           ...
4220    6Se31b5hPK
4221    AoirsULvxK
4222    OKcHs8DxA8
4223    0b3wzAqwax
4224    iEfy9h6Nzm
Name: item_id_10, Length: 4225, dtype: object

In [49]:
best.to_csv('runs/private-test-attempt-1/LightGCN_new_cluster_top10.csv', header=None, index=None)

# Push top 10 - 15 and new items up to top 5

In [142]:
best.head()

,user_id,item_id_1,item_id_2,item_id_3,item_id_4,item_id_5,item_id_6,item_id_7,item_id_8,item_id_9,...,item_id_991,item_id_992,item_id_993,item_id_994,item_id_995,item_id_996,item_id_997,item_id_998,item_id_999,item_id_1000
0,NcVPv81tzp,mwOc6vrVPi,oNn8dJXhM8,NZ6ZRExaU5,3tljNC7rIT,av2irHMO5f,IzLVUKs7uQ,wvulby9Vbm,o9yXO6Ak9I,q4bgY20S3L,...,wuxyl7VhE9,3AogAjK3kY,vy9wUsasAg,38YRAfjTC4,brGYGGFX4e,ZAsaiLlrZq,zjiExpN9uw,CthVhk4IIv,cFfT0AEdOb,FqyjUN4Rhl
1,C5ihgxLcrb,6jy1DwPo7L,u0KbwAhFgw,pUUgxbyvTC,41uJKXzbXd,f1dROAFg11,7NudKUsc5y,WjZUWFn3s9,kk3smPWhZf,O5nMvWF9dA,...,kp3MxtQ2Bj,B3oqKT10l0,qOg25LQeVV,vf96p77kez,bAtq3ygsLw,061nstrHvn,e404cyyJnR,UZLFYQnmym,d7MfqB64c3,huMnOiuSv1
2,ljMBWT9UXW,qwL2TeeksN,SXR8XvUPF1,OqbDoGrQBw,4I1KjMiSzV,1M0GtQfkUA,9hEAtPFlVc,TbMR37f6EX,qfMR0pa5jB,Hf6NKeCrqS,...,YVOVdSA9CQ,j2yCzYfp2j,y0JASRGqp8,SGFkpQe1TG,XmDINMQQg1,tvvWr1BHsf,7OU6tWwJWk,kuxZNvSVBf,jGsDd0jdbF,Dr64EGawuu
3,WZXCQtOWJt,xbfyEc4bwt,dQoIYlX2wJ,V6S3fAvyI9,0CpYs5b1cE,SzPkpQ35GK,yDU5yTDtxq,rGAG9phqUn,joDpuUf5SE,10MawcxCHm,...,TUOyX6Edy4,d69h3eVoNt,p5obG12NGj,wA2r6w1Z3F,AUMgblChwY,DUzL3jV5WR,kKfwgMRbeU,h8CYmT2joP,mAfEd2XxBR,4pYokzc1Ph
4,xlB2rvpQKu,glxC1XunRu,6TVXzSHJ63,YoxZfKJWnO,SwfZjYJfFW,qISW4xHwxJ,3xlCZg2BvX,HU5JUN8z0V,asNrzYAAKy,j5Uavgd0Wu,...,cQK77JSCis,ZUxwFeB411,PTfPPdoy5o,qOTFqgewtu,sUaT9mq1Bl,z4qiY70Lzs,3b4PyCAq2O,3QoCBriOGk,4mh04joXPq,Hg5IDU3eqr

In [143]:
for idx, row in best.iterrows():
    if row['user_id'] in keys:
        # Move values from item_10, item_11, item_12, item_13, item_14 to item_5, item_6, item_7, item_8, item_9
        best.loc[idx, 'item_id_5'] = row['item_id_10']
        best.loc[idx, 'item_id_6'] = row['item_id_11']
        best.loc[idx, 'item_id_7'] = row['item_id_12']
        best.loc[idx, 'item_id_8'] = row['item_id_13']
        best.loc[idx, 'item_id_9'] = row['item_id_14']

In [145]:
best.to_csv('submission/predict_0.5886_push10_14_to_5_9.csv', header=None, index=None)

In [ ]:
from tqdm.notebook import tqdm
return_list = []
for t in tqdm(test.values):
    userid = t[0]
    df = pd.DataFrame(t[1:1001]).merge(pd.DataFrame(list_all_item), how='outer', indicator=True)
    df = df[df['_merge'] == 'left_only']

    list_item = df[0].values
    return_list.append([userid, *list_item])

In [ ]:
return_df = pd.DataFrame(return_list)

In [ ]:
# Fill remanining cells as nan value to make submit file eligible
for i in range(len(return_df.columns), 1001):
    return_df[i] = np.nan

In [ ]:
return_df.fillna("0").to_csv(f"{output_dir}/predict.csv", header=None, index=False)

In [ ]:
!cd $output_dir && zip predict.zip predict.csv

In [ ]:
l = [1, 2, 4, 4,5]
for i in l.:
    i = 1
l